---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
activity <- read.csv("activity.csv", header = TRUE)


## What is mean total number of steps taken per day?
totalsteps <- aggregate(steps ~ date, activity, FUN = sum)
hist(totalsteps$steps, main="Total Number of Steps per Day", col = "blue" ,xlab= "Number of Steps" )
mean <- mean(totalsteps$steps, na.rm =  TRUE)
median <- median(totalsteps, na.rm = TRUE)



## What is the average daily activity pattern?
library(ggplot2)
meanstep <- aggregate(steps ~ interval, activity, mean)
ggplot(data = meanstep, aes(x=interval, y= steps))+geom_line(color="blue")+ggtitle("Average Daily Activity Pattern")+xlab("5-minute Interval")+ylab("Average Number of Steps")+theme(plot.title = element_text(hjust = 0.5))
maxstep <- meanstep[which.max(meanstep$steps),]


## Imputing missing values
missval <- is.na(activity$steps)
meanstep <- aggregate(steps ~ interval, activity, mean)
filledindata <- transform(activity, steps=ifelse(is.na(activity$steps),meanstep$steps[match(activity$interval,meanstep$interval)], activity$steps ))
filledin <- aggregate(steps ~ date, filledindata, FUN = sum)
hist(filledin$steps, main= "Total Numbers of Steps per Day - Imputed", col="green" ,xlab = "Number of Steps")


## Are there differences in activity patterns between weekdays and weekends?
meanstep <- aggregate(steps ~ interval, activity, mean)
filledindata <- transform(activity, steps=ifelse(is.na(activity$steps),meanstep$steps[match(activity$interval,meanstep$interval)], activity$steps ))
type <- function(date)  {day <- weekdays(date)
                        if (day %in% c('Monday','Tuesday', 'Wednesday','Thursday','Friday'))
                                return("weekday")
                                else if (day %in% c('Saturday','Sunday'))
                                        return("weekend")
                                else
                                        stop ("Invalid Date Format.")}
filledindata$date <- as.Date(filledindata$date)
filledindata$day <- sapply(filledindata$date, FUN = type)
meanstepbyday <- aggregate(steps ~ interval + day, filledindata, mean)
ggplot(data = meanstepbyday, aes(x=interval, y=steps))+theme_bw() +geom_line(color="blue")+facet_grid(day ~.)+ggtitle("Activity Pattern")+xlab("Interval")+ylab("Number of Steps")+theme(plot.title = element_text(hjust = 0.5))
